### ISSUE TITLE
New Component 

### ISSUE THREAD

**Issue by shubhamaher2** [shubhamaltpi/Ionic-UI-UX#4]
Make new component 
![WhatsApp Image 2024-03-18 at 7 27 42 PM](https://github.com/shubhamaltpi/Ionic-UI-UX/assets/139440042/3be9bd6b-2a5f-4f79-820b-c02c3db96d8b)

**Comment by salman7875** [comment]
Okay, i will do it

**Comment by shubhamaher2** [comment]
Okay

**Comment by shubhamaher2** [comment]
Done
